# OpenSRA.cmake
# Usage:
#   include(path/to/OpenSRA.cmake)
#   simcenter_add_opensra(<target>)
#
# Mirrors R2DTool/R2D.cmake. Adds OpenSRA's own sources/headers (from OpenSRA.pro, minus
# main.cpp which is listed at top level) plus the subset of R2DTool sources OpenSRA borrows
# (from OpenSRACommon.pri's $$PATH_TO_R2D entries).
#
# NOTE: the SimCenterCommon Workflow + RandomVariables + Common sources that OpenSRACommon.pri
# and Common.pri used to pull in are intentionally NOT listed here. They are supplied by the
# helper modules invoked from CMakeLists.txt (simcenter_add_workflow / simcenter_add_randomvariables
# / simcenter_add_common). Listing them here too would double-add the same source files.

set(OPENSRA_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}")

function(simcenter_add_opensra target)

  set(dir "${OPENSRA_MODULE_DIR}")
  set(r2d "${dir}/../R2DTool")

  target_include_directories(${target} PRIVATE
    # OpenSRA's own dirs (OpenSRA.pro INCLUDEPATH)
    "${dir}"
    "${dir}/Utils"
    "${dir}/styles"
    "${dir}/UIWidgets"
    "${dir}/JsonWidgets"
    "${dir}/ModelViewItems"
    # Borrowed R2DTool dirs (OpenSRACommon.pri INCLUDEPATH)
    "${r2d}"
    "${r2d}/UIWidgets"
    "${r2d}/Tools"
    "${r2d}/Events"
    "${r2d}/Events/UI"
    "${r2d}/GraphicElements"
    "${r2d}/ModelViewItems"
    "${r2d}/systemPerformanceWidgets"
  )

  set(SOURCES
    # ---- OpenSRA's own sources (OpenSRA.pro, minus main.cpp) ----
    "${dir}/JsonWidgets/JsonDefinedWidget.cpp"
    "${dir}/JsonWidgets/JsonGroupBoxWidget.cpp"
    "${dir}/JsonWidgets/JsonComboBox.cpp"
    "${dir}/JsonWidgets/JsonLineEdit.cpp"
    "${dir}/JsonWidgets/JsonLabel.cpp"
    "${dir}/JsonWidgets/JsonCheckBox.cpp"
    "${dir}/JsonWidgets/JsonWidget.cpp"
    "${dir}/JsonWidgets/JsonStackedWidget.cpp"
    "${dir}/JsonWidgets/SimCenterJsonWidget.cpp"
    "${dir}/ModelViewItems/ComboBoxDelegate.cpp"
    "${dir}/ModelViewItems/ButtonDelegate.cpp"
    "${dir}/ModelViewItems/RV.cpp"
    "${dir}/ModelViewItems/RVTableView.cpp"
    "${dir}/ModelViewItems/RVTableModel.cpp"
    "${dir}/ModelViewItems/MixedDelegate.cpp"
    "${dir}/ModelViewItems/LineEditDelegate.cpp"
    "${dir}/ModelViewItems/LabelDelegate.cpp"
    "${dir}/ModelViewItems/StringListDelegate.cpp"
    "${dir}/UIWidgets/AddToRunListWidget.cpp"
    "${dir}/UIWidgets/ClickableLabel.cpp"
    "${dir}/UIWidgets/EDPLandslideWidget.cpp"
    "${dir}/UIWidgets/MonteCarloSamplingWidget.cpp"
    "${dir}/UIWidgets/FixedResidualsSamplingWidget.cpp"
    "${dir}/UIWidgets/OpenSHAWidget.cpp"
    "${dir}/UIWidgets/OpenSRAComponentSelection.cpp"
    "${dir}/UIWidgets/OpenSRAPostProcessor.cpp"
    "${dir}/UIWidgets/OpenSRAPreProcessor.cpp"
    "${dir}/UIWidgets/UncertaintyQuantificationWidget.cpp"
    "${dir}/UIWidgets/WidgetFactory.cpp"
    "${dir}/UIWidgets/DecisionVariableWidget.cpp"
    "${dir}/UIWidgets/SourceCharacterizationWidget.cpp"
    "${dir}/UIWidgets/CustomVisualizationWidget.cpp"
    "${dir}/UIWidgets/PipelineNetworkWidget.cpp"
    "${dir}/UIWidgets/EngDemandParamWidget.cpp"
    "${dir}/UIWidgets/EngineeringDemandParameterWidget.cpp"
    "${dir}/UIWidgets/MultiComponentEDPWidget.cpp"
    "${dir}/UIWidgets/MultiComponentDMWidget.cpp"
    "${dir}/UIWidgets/MultiComponentDVWidget.cpp"
    "${dir}/UIWidgets/IntensityMeasureWidget.cpp"
    "${dir}/UIWidgets/DamageMeasureWidget.cpp"
    "${dir}/UIWidgets/RandomVariablesWidget.cpp"
    "${dir}/UIWidgets/UserInputCPTWidget.cpp"
    "${dir}/UIWidgets/GeospatialDataWidget.cpp"
    "${dir}/UIWidgets/GenericModelWidget.cpp"
    "${dir}/UIWidgets/StateWidePipelineWidget.cpp"
    "${dir}/UIWidgets/BayAreaPipelineWidget.cpp"
    "${dir}/UIWidgets/LosAngelesPipelineWidget.cpp"
    "${dir}/UIWidgets/NDAStateWidePipelineWidget.cpp"
    "${dir}/UIWidgets/NDABayAreaPipelineWidget.cpp"
    "${dir}/UIWidgets/UserDefinedGroundMotionWidget.cpp"
    "${dir}/Utils/EventFilter.cpp"
    "${dir}/ResultsWidget.cpp"
    "${dir}/WorkflowAppOpenSRA.cpp"
    "${dir}/WorkflowAppWidget.cpp"
    "${dir}/MainWindowWorkflowApp.cpp"
    "${dir}/LocalApplication.cpp"
    "${dir}/OpenSRAPreferences.cpp"
    "${dir}/GeneralInformationWidget.cpp"
    "${dir}/RunWidget.cpp"

    # ---- Borrowed R2DTool sources (OpenSRACommon.pri, $$PATH_TO_R2D) ----
    "${r2d}/Tools/CSVReaderWriter.cpp"
    "${r2d}/Tools/XMLAdaptor.cpp"
    "${r2d}/Tools/AssetInputDelegate.cpp"
    "${r2d}/Tools/AssetFilterDelegate.cpp"
    "${r2d}/Tools/ComponentDatabase.cpp"
    "${r2d}/Tools/ComponentDatabaseManager.cpp"
    "${r2d}/Tools/TablePrinter.cpp"
    "${r2d}/Tools/SimCenterUnitsCombo.cpp"
    "${r2d}/Events/UI/SiteConfig.cpp"
    "${r2d}/Events/UI/site.cpp"
    "${r2d}/Events/UI/SiteGrid.cpp"
    "${r2d}/Events/UI/GridDivision.cpp"
    "${r2d}/Events/UI/Location.cpp"
    "${r2d}/Events/UI/SiteScatter.cpp"
    "${r2d}/UIWidgets/LoadResultsDialog.cpp"
    "${r2d}/UIWidgets/MultiComponentR2D.cpp"
    "${r2d}/GraphicElements/GridNode.cpp"
    "${r2d}/GraphicElements/NodeHandle.cpp"
    "${r2d}/GraphicElements/RectangleGrid.cpp"
    "${r2d}/UIWidgets/LineAssetInputWidget.cpp"
    "${r2d}/UIWidgets/PointAssetInputWidget.cpp"
    "${r2d}/UIWidgets/CSVWellsCaprocksInputWidget.cpp"
    "${r2d}/UIWidgets/GISWellsCaprocksInputWidget.cpp"
    "${r2d}/UIWidgets/CSVAboveGroundGasComponentInputWidget.cpp"
    "${r2d}/UIWidgets/GISAboveGroundGasComponentInputWidget.cpp"
    "${r2d}/UIWidgets/AssetInputWidget.cpp"
    "${r2d}/UIWidgets/CRSSelectionWidget.cpp"
    "${r2d}/UIWidgets/ShakeMapWidget.cpp"
    "${r2d}/UIWidgets/GISAssetInputWidget.cpp"
    "${r2d}/UIWidgets/GISMapWidget.cpp"
    "${r2d}/UIWidgets/GISGasNetworkInputWidget.cpp"
    "${r2d}/UIWidgets/GroundMotionStation.cpp"
    "${r2d}/UIWidgets/GroundMotionTimeHistory.cpp"
    "${r2d}/UIWidgets/SimCenterUnitsWidget.cpp"
    "${r2d}/UIWidgets/UserInputFaultWidget.cpp"
    "${r2d}/ModelViewItems/CustomListWidget.cpp"
    "${r2d}/ModelViewItems/MutuallyExclusiveListWidget.cpp"
    "${r2d}/ModelViewItems/ComponentTableModel.cpp"
    "${r2d}/ModelViewItems/ComponentTableView.cpp"
    "${r2d}/ModelViewItems/ListTreeModel.cpp"
  )

  set(HEADERS
    # ---- OpenSRA's own headers (OpenSRA.pro) ----
    "${dir}/JsonWidgets/JsonDefinedWidget.h"
    "${dir}/JsonWidgets/JsonComboBox.h"
    "${dir}/JsonWidgets/JsonLineEdit.h"
    "${dir}/JsonWidgets/JsonLabel.h"
    "${dir}/JsonWidgets/JsonCheckBox.h"
    "${dir}/JsonWidgets/JsonWidget.h"
    "${dir}/JsonWidgets/JsonStackedWidget.h"
    "${dir}/JsonWidgets/SimCenterJsonWidget.h"
    "${dir}/JsonWidgets/JsonGroupBoxWidget.h"
    "${dir}/ModelViewItems/ComboBoxDelegate.h"
    "${dir}/ModelViewItems/ButtonDelegate.h"
    "${dir}/ModelViewItems/RV.h"
    "${dir}/UIWidgets/AddToRunListWidget.h"
    "${dir}/UIWidgets/ClickableLabel.h"
    "${dir}/UIWidgets/EDPLandslideWidget.h"
    "${dir}/UIWidgets/MonteCarloSamplingWidget.h"
    "${dir}/UIWidgets/FixedResidualsSamplingWidget.h"
    "${dir}/UIWidgets/OpenSHAWidget.h"
    "${dir}/UIWidgets/OpenSRAComponentSelection.h"
    "${dir}/UIWidgets/OpenSRAPostProcessor.h"
    "${dir}/UIWidgets/OpenSRAPreProcessor.h"
    "${dir}/ResultsWidget.h"
    "${dir}/UIWidgets/UncertaintyQuantificationWidget.h"
    "${dir}/UIWidgets/WidgetFactory.h"
    "${dir}/UIWidgets/RandomVariablesWidget.h"
    "${dir}/UIWidgets/UserInputCPTWidget.h"
    "${dir}/UIWidgets/GeospatialDataWidget.h"
    "${dir}/UIWidgets/GenericModelWidget.h"
    "${dir}/UIWidgets/StateWidePipelineWidget.h"
    "${dir}/UIWidgets/BayAreaPipelineWidget.h"
    "${dir}/UIWidgets/LosAngelesPipelineWidget.h"
    "${dir}/UIWidgets/NDAStateWidePipelineWidget.h"
    "${dir}/UIWidgets/NDABayAreaPipelineWidget.h"
    "${dir}/Utils/EventFilter.h"
    "${dir}/WorkflowAppOpenSRA.h"
    "${dir}/WorkflowAppWidget.h"
    "${dir}/MainWindowWorkflowApp.h"
    "${dir}/LocalApplication.h"
    "${dir}/OpenSRAPreferences.h"
    "${dir}/RunWidget.h"
    "${dir}/UIWidgets/DecisionVariableWidget.h"
    "${dir}/UIWidgets/SourceCharacterizationWidget.h"
    "${dir}/UIWidgets/CustomVisualizationWidget.h"
    "${dir}/UIWidgets/PipelineNetworkWidget.h"
    "${dir}/UIWidgets/EngDemandParamWidget.h"
    "${dir}/UIWidgets/EngineeringDemandParameterWidget.h"
    "${dir}/UIWidgets/MultiComponentEDPWidget.h"
    "${dir}/UIWidgets/MultiComponentDMWidget.h"
    "${dir}/UIWidgets/MultiComponentDVWidget.h"
    "${dir}/GeneralInformationWidget.h"
    "${dir}/UIWidgets/IntensityMeasureWidget.h"
    "${dir}/UIWidgets/DamageMeasureWidget.h"
    "${dir}/UIWidgets/UserDefinedGroundMotionWidget.h"
    "${dir}/ModelViewItems/RVTableView.h"
    "${dir}/ModelViewItems/RVTableModel.h"
    "${dir}/ModelViewItems/MixedDelegate.h"
    "${dir}/ModelViewItems/LineEditDelegate.h"
    "${dir}/ModelViewItems/LabelDelegate.h"
    "${dir}/ModelViewItems/StringListDelegate.h"

    # ---- Borrowed R2DTool headers (OpenSRACommon.pri, $$PATH_TO_R2D) ----
    "${r2d}/Tools/XMLAdaptor.h"
    "${r2d}/Tools/CSVReaderWriter.h"
    "${r2d}/Tools/AssetInputDelegate.h"
    "${r2d}/Tools/AssetFilterDelegate.h"
    "${r2d}/Tools/ComponentDatabase.h"
    "${r2d}/Tools/TablePrinter.h"
    "${r2d}/Tools/SimCenterUnitsCombo.h"
    "${r2d}/Tools/ComponentDatabaseManager.h"
    "${r2d}/Events/UI/SiteConfig.h"
    "${r2d}/Events/UI/site.h"
    "${r2d}/Events/UI/SiteGrid.h"
    "${r2d}/Events/UI/GridDivision.h"
    "${r2d}/Events/UI/Location.h"
    "${r2d}/Events/UI/SiteScatter.h"
    "${r2d}/Events/UI/JsonSerializable.h"
    "${r2d}/UIWidgets/LoadResultsDialog.h"
    "${r2d}/UIWidgets/MultiComponentR2D.h"
    "${r2d}/GraphicElements/GridNode.h"
    "${r2d}/GraphicElements/NodeHandle.h"
    "${r2d}/GraphicElements/RectangleGrid.h"
    "${r2d}/UIWidgets/LineAssetInputWidget.h"
    "${r2d}/UIWidgets/PointAssetInputWidget.h"
    "${r2d}/UIWidgets/CSVWellsCaprocksInputWidget.h"
    "${r2d}/UIWidgets/GISWellsCaprocksInputWidget.h"
    "${r2d}/UIWidgets/CSVAboveGroundGasComponentInputWidget.h"
    "${r2d}/UIWidgets/GISAboveGroundGasComponentInputWidget.h"
    "${r2d}/UIWidgets/AssetInputWidget.h"
    "${r2d}/UIWidgets/CRSSelectionWidget.h"
    "${r2d}/UIWidgets/ShakeMapWidget.h"
    "${r2d}/UIWidgets/GISAssetInputWidget.h"
    "${r2d}/UIWidgets/GISMapWidget.h"
    "${r2d}/UIWidgets/GISGasNetworkInputWidget.h"
    "${r2d}/UIWidgets/GroundMotionStation.h"
    "${r2d}/UIWidgets/GroundMotionTimeHistory.h"
    "${r2d}/UIWidgets/SimCenterUnitsWidget.h"
    "${r2d}/UIWidgets/UserInputFaultWidget.h"
    "${r2d}/ModelViewItems/CustomListWidget.h"
    "${r2d}/ModelViewItems/MutuallyExclusiveListWidget.h"
    "${r2d}/ModelViewItems/ComponentTableModel.h"
    "${r2d}/ModelViewItems/ComponentTableView.h"
    "${r2d}/ModelViewItems/ListTreeModel.h"
  )

  target_sources(${target} PRIVATE ${SOURCES} ${HEADERS})

  # OpenSRAUserPass.h holds credentials and is gitignored (absent on clean checkouts).
  # Add it only when present, mirroring R2D's R2DUserPass.h handling.
  if(EXISTS "${dir}/OpenSRAUserPass.h")
    target_sources(${target} PRIVATE "${dir}/OpenSRAUserPass.h")
  endif()

endfunction()
